name: cheap_tickets_app
description: "A Flutter application to pass test!"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #service locator
  get_it: ^7.7.0
  injectable: ^2.4.1

  #state management  
  flutter_bloc: ^8.1.5
  rxdart: ^0.27.7

  #sereliazitaion, comapare objects
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0

  #routing
  auto_route: ^8.1.3

  #work with api
  dio: ^5.4.3+1
  retrofit: ^4.1.0

  #localizations,internationalizations
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter


  #database
  shared_preferences: ^2.2.3

  #UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  
  
  
  

  
  

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: '>=2.3.0 <4.0.0'
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.6.2
  retrofit_generator: '>=7.0.0 <8.0.0'
  hive_generator: any

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/svg/bottom_nav_bar_icons/
    - assets/svg/icons/
    - assets/images/offers/
    - assets/images/recommendations/
    - assets/dummy_data/

  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 700
       